name: Build&Deploy

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1

    - uses: actions/checkout@v2

    - name: Build
      run: |
        npm i
        npm run build
    - name: Copy Files
      run: |
        cp CNAME dist/CNAME
        cp README.MD dist/README.MD
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
